[Project]
IsCreateProjectDirectory = true
IsProjectFileRowEnabled = false
IsProjectNameRowEnabled = true
IsClassNameRowEnabled = false
IsDotnetVersionRowEnabled = true
IsWindowsSDKVersionRowEnabled = true
IsOutputDirRowEnabled = true
IsOutputEnabled = true

[MAUI]
IsCreateProjectDirectory = true
IsProjectFileRowEnabled = false
IsProjectNameRowEnabled = true
IsClassNameRowEnabled = false
IsDotnetVersionRowEnabled = true
IsWindowsSDKVersionRowEnabled = true
IsOutputDirRowEnabled = true
IsOutputEnabled = true

[Blazor]
IsCreateProjectDirectory = true
IsProjectFileRowEnabled = false
IsProjectNameRowEnabled = true
IsClassNameRowEnabled = false
IsDotnetVersionRowEnabled = true
IsWindowsSDKVersionRowEnabled = true
IsOutputDirRowEnabled = true
IsOutputEnabled = true

["*"]
IsCreateProjectDirectory = false
IsProjectFileRowEnabled = true
IsProjectNameRowEnabled = true
IsClassNameRowEnabled = true
IsDotnetVersionRowEnabled = false
IsWindowsSDKVersionRowEnabled = false
IsOutputDirRowEnabled = true
IsOutputEnabled = true

